name: dimp
description: Decentralized Instant Messaging Protocol (DIMP).
version: 2.2.1
homepage: https://github.com/dimchat/core-dart
repository: https://github.com/dimchat/core-dart
issue_tracker: https://github.com/dimchat/core-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dkd: ^2.2.1
  mkm: ^2.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
